using System;
using System.Net;

namespace SAL.Interface.MessageQueue.Message
{
	public class MailHeaderDto
	{
		/// <summary>ID of the message generated by the server</summary>
		public String MessageId { get; set; }
		/// <summary>Received date of the message in Universal Time</summary>
		public DateTime Date { get; set; }
		/// <summary>Sender IP address</summary>
		public IPAddress SenderIp { get; set; }
	}
}